language: node_js

services:
    - docker   
before_install:
    - docker build -t hbirkdale/nohnoh-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true hbirkdale/nohnoh-react npm run test